### ISSUE TITLE
[BUG]无法启动

### ISSUE THREAD

**Issue by Brx86** [Icalingua-plus-plus/Icalingua3#2]
**Describe the bug / 描述**

执行`pnpm dev`，报错退出

<details>
<summary>终端输出</summary>

    ❯ pnpm dev

    > icalingua@3.0.0 dev /home/aya/git/Icalingua3
    > pnpm --filter @icalingua/*end dev

    Scope: 2 of 5 workspace projects
    backend dev$ ts-node ./src/index.ts -d
    │ ⚛ 09-19 14:41:11 [DEBUG] [info] MikroORM version: 5.4.1
    │ ⚛ 09-19 14:41:11 [DEBUG] [discovery] ORM entity discovery started, using TsMorphMetadataProvider
    │ ⚛ 09-19 14:41:11 [DEBUG] [discovery] - processing entity Message
    │ ⚛ 09-19 14:41:11 [DEBUG] [discovery] - using cached metadata for entity Message
    │ ⚛ 09-19 14:41:11 [DEBUG] [discovery] - processing entity ChatRoom
    │ ⚛ 09-19 14:41:11 [DEBUG] [discovery] - using cached metadata for entity ChatRoom
    │ ⚛ 09-19 14:41:11 [DEBUG] [discovery] - entity discovery finished, found 2 entities, took 41 ms
    │ ⚛ 09-19 14:41:11 [DEBUG] [info] MikroORM successfully connected to database /home/aya/git/Icalingua3/b
    │ /home/aya/git/Icalingua3/node_modules/.pnpm/@fastify+static@6.5.0/node_modules/@fastify/static/index.j
    │     throw new Error('"root" option must be an absolute path')
    │           ^
    │ Error: "root" option must be an absolute path
    │     at checkPath (/home/aya/git/Icalingua3/node_modules/.pnpm/@fastify+static@6.5.0/node_modules/@fast
    │     at checkRootPathForErrors (/home/aya/git/Icalingua3/node_modules/.pnpm/@fastify+static@6.5.0/node_
    │     at fastifyStatic (/home/aya/git/Icalingua3/node_modules/.pnpm/@fastify+static@6.5.0/node_modules/@
    │     at Plugin.exec (/home/aya/git/Icalingua3/node_modules/.pnpm/avvio@8.2.0/node_modules/avvio/plugin.
    │     at Boot.loadPlugin (/home/aya/git/Icalingua3/node_modules/.pnpm/avvio@8.2.0/node_modules/avvio/plu
    │     at processTicksAndRejections (node:internal/process/task_queues:82:21)
    └─ Failed in 7.5s
    frontend dev$ vite
    │   VITE v3.1.1  ready in 692 ms
    │   ➜  Local:   http://localhost:5173/
    │   ➜  Network: use --host to expose
    └─ Running...
    /home/aya/git/Icalingua3/backend:
     ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @icalingua/backend@1.0.0 dev: `ts-node ./src/index.ts -d`
    Exit status 1
     ELIFECYCLE  Command failed with exit code 1.

</details>

终端录屏 https://asciinema.org/a/mXLn43Z8WWT5sTBPntJFKtsuU

**To Reproduce / 复现过程**
```
pnpm i
pnpm dev
```

**Expected behavior / 预期的结果**

正常运行，可以在浏览器打开

**Screenshots / 截图**

![2022-09-19_14 57 32](https://user-images.githubusercontent.com/44391900/190964669-1a2fe1ba-250a-46c4-b4e3-eaa9884da144.png)

**System information / 系统信息**
 - OS: Arch Linux
 - Nodejs: v18.9.0
 - Pnpm: v7.12.0

**Comment by lixiang810** [comment]
先执行一遍 `pnpm build:frontend`

**Comment by Brx86** [comment]
> 先执行一遍 `pnpm build:frontend`

build之后dev还是会报错……我的操作是这样
https://asciinema.org/a/e9SQOZ9Egdmcx38sshdfOf7K8

**Comment by lixiang810** [comment]
`backend/utils/pathUtils.ts` 末尾加入一行：

```javascript
console.log({ root, staticPath });
```

并获取输出看看。

**Comment by Brx86** [comment]
> ```js
> console.log({ root, staticPath， url: import.meta.url });
> ```

│ {
│   root: 'home/aya/git/Icalingua3/',
│   staticPath: 'home/aya/git/Icalingua3/static',
│   url: 'file:///home/aya/git/Icalingua3/backend/src/utils/pathUtils.ts'
│ }

**Comment by lixiang810** [comment]
Fixed in a872459

pull 之后试试看

**Comment by Brx86** [comment]
> Fixed in [562edca](https://github.com/Icalingua-plus-plus/Icalingua3/commit/562edca4ab9ace05e131778c5f1dca30c58efb97)
> 
> pull 之后试试看

感谢，在pnpm keyctl之后pnpm dev可以正常运行了。请问网页里的地址和密钥应该填什么呢？

**Comment by lixiang810** [comment]
> 请问网页里的地址和密钥应该填什么呢？

- 地址：如果前后端都在你自己的电脑上，这一项可以留空。
- 密钥：`pnpm keyctl` - 查看已保存的密钥，复制输出。

值得注意的是， il3 的数据库结构尚未稳定，可能发生破坏性更改。

**Comment by Brx86** [comment]
非常感谢，运行起来了，大佬加油，未来可期👍🏻

**Comment by lixiang810** [comment]
a7a95af 以后改成了密码登录，不再需要使用 `keyctl` 来生成密钥，第一次登录时的密码会被保存。
