### ISSUE TITLE
Deepin 20.7版本，软件用一会就会闪退

### ISSUE THREAD

**Issue by chenmingjun2** [Icalingua-plus-plus/Icalingua3#5]
使用2.5.3版本就不会闪退。
版本：2.7.7,从2.6版本开始就有闪退情况
系统信息
![图片](https://user-images.githubusercontent.com/111257814/203290685-aeb1ed9f-bd0a-4c3d-b16f-7640f30c4c96.png)

**Comment by BeiyanYunyi** [comment]
这里是 Icalingua3，不是 Icalingua-plus-plus，版本号 2 开头的问题去[那边](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus)问。
